- name: Clone local Git project repository
  git:
    repo: /home/dhayanidhi-s/project_repository/
    dest: /var/lib/jenkins/workspace/project-pipeline/ci_cd_workspace/
    version: master
    force: yes
