- name: Create monitoring directory inside workspace
  file:
    path: "{{ build_path }}/monitoring"
    state: directory
    mode: '0755'

- name: Copy Docker Compose file to monitoring folder
  copy:
    src: docker-compose.yml      # This looks inside roles/monitor/files/
    dest: "{{ build_path }}/monitoring/docker-compose.yml"

- name: Start monitoring stack with Docker Compose
  command: docker-compose up -d
  args:
    chdir: "{{ build_path }}/monitoring"
