- name: Full DevOps Pipeline for Project
  hosts: local
  become: true
  vars:
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
  roles:
    - gitclone
    - build
    - test
    - dockerize
    - deploy
    - monitor
    - rollback
