---
- name: Full DevOps Pipeline
  hosts: local
  become: true

  vars:
    build_number: "{{ build_number }}"
    build_path: "{{ build_path }}"

  roles:
    - { role: build, tags: ['build'] }
    - { role: test, tags: ['test'] }
    - { role: dockerize, tags: ['dockerize'] }
    - { role: deploy, tags: ['deploy'] }
    - { role: monitor, tags: ['monitor'] }
    - { role: rollback, tags: ['rollback'] }
