- name: Copy Dockerfile to workspace
  copy:
    src: /home/dhayanidhi-s/Documents/dockerProjects/Dockerfile
    dest: "{{ build_path }}/Dockerfile"

- name: Build Docker image with unique version tag and 'latest'
  command: >
    docker build
    -t financial-calc:build-{{ build_number }}
    -t financial-calc:latest
    .
  args:
    chdir: "{{ build_path }}"

- name: Save successful build number to file
  copy:
    content: "{{ build_number }}"
    dest: "{{ build_path }}/last_success_build.txt"

- name: Tag current successful image as 'previous'
  shell: docker tag financial-calc:build-{{ build_number }} financial-calc:previous

